import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
// import { Inter } from "@next/font/google";
import Card from "@components/card/card";
import styles from "@/styles/Home.module.css";
import NiceModal from "@ebay/nice-modal-react";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {

	const handleGoToRoute = (user: string) => {
		const link = document.createElement("a")
		link.href = `https://calendly.com/${user}`
		link.target = "_blank"
		link.click()

	}

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
				{/* <link
					href="https://assets.calendly.com/assets/external/widget.css"
					rel="stylesheet"
				/> */}

				{/* <link
					href="https://assets.calendly.com/assets/external/widget.css"
					rel="stylesheet"
				/> */}
			</Head>
			<main className="w-screen h-screen flex flex-col justify-start items-center box-border pt-24">
				<div className="w-full h-max flex flex-col justify-center items-center gap-y-3 px-4">
					<h1 className=" text-4xl md:text-6xl lg:text-6xl font-bold text-center">
						Meeting with mentors
					</h1>
					<p className="text-lg font-normal text-gray-700 text-center mb-4 md:m-0 lg:m-0">
						Some kind of tagline here
					</p>
				</div>
				<div className="w-full h-max flex flex-row justify-center items-center gap-16 flex-wrap flex-1 mt-4">
					<Card
						onClick={() => handleGoToRoute("xelopsys")}
						title="teacherqwdqwd"
						extraCss="md:order-2"
						img="https://images.unsplash.com/photo-1673868077539-9c3120f78420?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80"
						btnText="Click"
					/>
					<Card
						onClick={() => { }}
						title="teacher123"
						extraCss="lg:[&:nth-child(2)]:mb-24 order-1 md:order-2 lg:order-2"
						img="https://images.unsplash.com/photo-1673868077539-9c3120f78420?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80"
						btnText="Click"
					/>
					<Card
						onClick={() => { }}
						extraCss="md:order-3"
						title="teacher"
						img="https://images.unsplash.com/photo-1673868077539-9c3120f78420?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80"
						btnText="Click"
					/>
				</div>
			</main>
			{/* <div
				className="calendly-inline-widget"
				data-url="https://calendly.com/xelopsys"
				style={{
					minWidth: "500px!important",
					height: "500px!important",
					// backgroundColor: "transparent!important",
				}}
			></div>
			<Script
				type="text/javascript"
				src="https://assets.calendly.com/assets/external/widget.js"
				async
			></Script> */}

			{/* <script
				src="https://assets.calendly.com/assets/external/widget.js"
				type="text/javascript"
				async
			></script>
			<script type="text/javascript">
				window.onload = function(){" "}
				{Calendly.initBadgeWidget({
					url: "https://calendly.com/xelopsys",
					text: "Schedule time with me",
					color: "#0069ff",
					textColor: "#ffffff",
					branding: true,
				})}
			</script> */}
			{/* <script
				src="https://assets.calendly.com/assets/external/widget.js"
				type="text/javascript"
				async
			></script>
			<a
				href=""
				onClick={() => {
					Calendly.initPopupWidget({ url: "https://calendly.com/xelopsys" });
					return false;
				}}
			>
				Schedule time with me
			</a> */}
			{/* <main className={styles.main}>
				<div className={styles.description}>
					<p>
						Get started by editing&nbsp;
						<code className={styles.code}>pages/index.tsx</code>
					</p>
					<div>
						<a
							href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
							target="_blank"
							rel="noopener noreferrer"
						>
							By{" "}
							<Image
								src="/vercel.svg"
								alt="Vercel Logo"
								className={styles.vercelLogo}
								width={100}
								height={24}
								priority
							/>
						</a>
					</div>
				</div>

				<div className={styles.center}>
					<Image
						className={styles.logo}
						src="/next.svg"
						alt="Next.js Logo"
						width={180}
						height={37}
						priority
					/>
					<div className={styles.thirteen}>
						<Image
							src="/thirteen.svg"
							alt="13"
							width={40}
							height={31}
							priority
						/>
					</div>
				</div>

				<div className={styles.grid}>
					<a
						href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						className={styles.card}
						target="_blank"
						rel="noopener noreferrer"
					>
						<h2 className={inter.className}>
							Docs <span>-&gt;</span>
						</h2>
						<p className={inter.className}>
							Find in-depth information about Next.js features and&nbsp;API.
						</p>
					</a>

					<a
						href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						className={styles.card}
						target="_blank"
						rel="noopener noreferrer"
					>
						<h2 className={inter.className}>
							Learn <span>-&gt;</span>
						</h2>
						<p className={inter.className}>
							Learn about Next.js in an interactive course with&nbsp;quizzes!
						</p>
					</a>

					<a
						href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						className={styles.card}
						target="_blank"
						rel="noopener noreferrer"
					>
						<h2 className={inter.className}>
							Templates <span>-&gt;</span>
						</h2>
						<p className={inter.className}>
							Discover and deploy boilerplate example Next.js&nbsp;projects.
						</p>
					</a>

					<a
						href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						className={styles.card}
						target="_blank"
						rel="noopener noreferrer"
					>
						<h2 className={inter.className}>
							Deploy <span>-&gt;</span>
						</h2>
						<p className={inter.className}>
							Instantly deploy your Next.js site to a shareable URL
							with&nbsp;Vercel.
						</p>
					</a>
				</div>
			</main> */}
		</div>
	);
}
